### ISSUE TITLE
Preview component Hello-World return 404 page 

### ISSUE THREAD

**Issue by MarzV** [bettyblocks/cli#58]
Following your usage chapter for setting-up the project the components preview renders a 404 page. The preview renders a mistake. Can you please check out the correct procedure for running the hello-world component.

**Comment by NiekBetty** [comment]
Hi @MarzV,

Thanks for your feedback.

After some research we found out that `npm` and `yarn` installs dependencies in different locations relative to each other.

E.g.:

`npm install -g @betty-blocks/cli` installs preview at:
`node_modules/@betty-blocks/cli/node_modules/@betty-blocks/preview`

where `yarn global add cli` installs preview add:
`node_modules/@betty-blocks/preview`

A temporary solution is to install the cli globally using `yarn` instead of `npm`. We will fix this issue in the future.

**Comment by MarzV** [comment]
Hey NiekBetty, thnkz for that additional info. I leave this issue open until fix is merged in master branche.

**Comment by NiekBetty** [comment]
Hi @MarzV,

This issue is solved with the latest release.
